# Enable the most aggressive optimizations (Full Mode)
android.enableR8.fullMode=true

# Speed up the build and reduce APK size further
android.r8.optimizedResourceShrinking=true

# Parallel builds to speed up GitHub Actions
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Android TV/Box Specific: Ensure native libs are handled correctly
android.useAndroidX=true
android.enableJetifier=false
android.defaults.buildfeatures.resvalues=true
