name: Build Debug APK

on:
  push:
    branches:
      - devel
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          # We disable internal caching to keep the environment pristine
          cache: '' 

      - name: Build Debug APK
        # -g .gradle-home ensures we use a fresh config directory
        # -D...= override forces the phantom property to be ignored
        run: |
          ./gradlew assembleDebug \
            --no-daemon \
            --no-build-cache \
            -g .gradle-home \
            -Dorg.gradle.project.android.bundle.enableUncompressedNativeLibs=

      - name: Upload ArmV7a Debug APK
        uses: actions/upload-artifact@v7
        with:
          name: Kotatsu-Debug-ArmV7a
          path: app/build/outputs/apk/debug/*-armeabi-v7a-debug.apk
