name: Release Build & Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump_version.outputs.new_tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Generate and Bump Tag Version
        id: bump_version
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          PRERELEASE: false

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: wrapper

      - name: Build Release APK
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > release.keystore
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/release.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.RELEASE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.RELEASE_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.RELEASE_KEY_PASSWORD }} \
            --no-daemon --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v7
        with:
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
          archive: false 

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download APK from build job
        uses: actions/download-artifact@v8
        with:
          path: ./ready_apks
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3.0.1
        with:
          tag_name: ${{ needs.build.outputs.new_tag }}
          name: "Release ${{ needs.build.outputs.new_tag }}"
          body: |
            ### Automated Release
          files: "./ready_apks/**/*.apk"
          generate_release_notes: true
          draft: false
          prerelease: false
